/**
 * Rotating hints shown at the bottom of the app sidebar.
 * Edit this file only — timing lives next to the array.
 */

/** How long each tip stays visible (ms). */
export const SIDEBAR_TIP_INTERVAL_MS = 14_000;

export const SIDEBAR_TIPS: readonly string[] = [
  "Workspace files expire after 24h; re-uploading the same video can reuse prior context for faster crops. Configure S3, Drive, and YouTube in Settings.",
  "The pipeline runs in three stages: ingest (transcribe), plan (LLM cuts), then render (FFmpeg). You can start all three from a run.",
  "Set a primary LLM in Settings and add ordered fallbacks—recoverable API errors automatically try the next profile.",
  "No API key yet? Use “Run without LLM” for a heuristic cut plan, then render still produces longform and shortform MP4s.",
  "Transcription can use local faster-whisper (tiny), OpenAI whisper-1, or AssemblyAI—pick under Settings → Transcription.",
  "Optional web search (Tavily, Brave, DuckDuckGo, …) helps the plan step; configure main + fallback under Settings → Search.",
  "For live logs in the browser, set NEXT_PUBLIC_API_URL to an API URL your browser can reach—otherwise the UI polls about once per second.",
  "Heavy or isolated runs: enable Docker workers (CLIPENGINE_USE_DOCKER_WORKERS) so each job runs in its own container sharing workspace data.",
  "Import from allowlisted folders, uploads, YouTube URLs, live streams, Drive, S3, or the catalog—bind mounts are documented under Help.",
  "Catalog sync indexes metadata only; “from catalog” materializes the file into a run workspace before ingest starts.",
  "Add planning context (folder paths, titles) so the LLM understands series, episodes, or campaign names when proposing cuts.",
  "MKV and some MOV files may have multiple audio tracks—pick the right stream on the run page before starting the pipeline.",
  "After render, send clips to workspace, Google Drive, S3, a registered local bind path, SMB (LAN only), or YouTube—per run.",
  "YouTube upload quota is per Google Cloud project, not per channel. Connect multiple accounts in Settings → YouTube if needed.",
  "Live capture uses yt-dlp with a max duration cap (CLIPENGINE_LIVE_MAX_SECONDS); stop early from the run when you’re done.",
  "Publishing presets in Settings control default titles and descriptions for exports and YouTube—tune before bulk uploads.",
  "Automation can chain runs—check the Automation page when you want repeatable workflows across sources.",
  "DuckDuckGo search needs no API key; for production reliability, prefer an API-backed provider as your main search.",
  "SQLite stores Settings; the API applies them at the start of each run, including in ephemeral worker processes.",
  "Behind a reverse proxy, set CLIPENGINE_PUBLIC_URL so Google OAuth redirects for Drive and YouTube resolve correctly.",
  "First-run Setup only needs an admin login; you can add LLM and Tavily keys later under Settings.",
  "CORS_ORIGINS lists which browser origins may call the API—adjust when you host the web app on a new domain.",
  "CLIPENGINE_DATA_DIR holds SQLite; CLIPENGINE_WORKSPACE holds run uploads and renders—back up both for a full restore.",
  "Merge Settings → Storage → Local path with CLIPENGINE_IMPORT_ROOTS so directory import sees every folder you intend.",
  "CLIPENGINE_WORKER_GPUS (e.g. all) passes GPUs into worker containers for faster local Whisper—skip on CPU-only hosts.",
  "CLIPENGINE_WORKER_DOCKER_RUN_ARGS can add extra volume binds so workers see the same host paths as the API.",
  "Production Compose bakes the web image; dev Compose hot-reloads Next and uvicorn—see docs/docker.md when upgrading.",
  "The web app proxies /api-engine to the API—use one origin in dev (e.g. localhost:3000) unless you set NEXT_PUBLIC_API_URL.",
  "Batch folder import can shuffle files and add a title_prefix—handy for large libraries or A/B ordering experiments.",
  "Heuristic plans skip LLM prose: publish_description may be empty until you edit metadata or rerun with an LLM.",
  "Download a render ZIP to get publish.txt and publish_metadata.json next to each clip—useful for manual uploads.",
  "Shortform thumbnails use FFmpeg cropdetect to trim letterboxing; longform thumbs sample the full frame.",
  "Tune clip length bounds and snap slack under Settings → Pipeline (or clipengine_* env vars) to match your format.",
  "Search set to auto picks the first API-backed provider with a key; with none, DuckDuckGo is the default.",
  "Tavily, Brave, Exa, SearXNG, and other providers each have env names—Settings writes the same keys SQLite expects.",
  "Reconnect Google Drive OAuth after scope changes so uploads keep working with the newer permissions.",
  "S3-compatible endpoints (MinIO, R2, etc.) work: set region, bucket, keys, and optional custom endpoint in Settings.",
  "YouTube output can map clips to one channel, rotate channels, pick randomly, or broadcast every clip to all selected channels.",
  "Cancel stops work in progress; live YouTube capture sends SIGTERM to yt-dlp so partial files can still validate.",
  "CLIPENGINE_LIVE_MIN_BYTES avoids marking a capture ready until the file is large enough to be real media.",
  "CLIPENGINE_YTDLP_EXTRA_ARGS tweaks VOD downloads; CLIPENGINE_LIVE_YTDLP_EXTRA_ARGS only affects live capture.",
  "Library and Runs keep history—use them to reopen old jobs without hunting the filesystem.",
  "Import roots are allowlisted for security: only registered paths (plus workspace) appear in directory pickers.",
  "SMB output is for private LANs or VPNs—never expose TCP 445 to the public internet.",
  "For a remote NAS from a VPS, Tailscale or S3/Drive is usually simpler than raw SMB across the open internet.",
  "The engine uses SQLite WAL so the API and workers can update run status safely at the same time.",
  "Anthropic and OpenAI-compatible profiles can coexist—chain order decides who plans first when you start a run.",
  "OpenAI transcription keys can come from a different profile than the planner if your chain includes multiple vendors.",
  "Render writes render_activity.json early—refresh the run page to watch encode progress clip by clip.",
  "Docs in the repo cover pipeline stages, bind mounts, YouTube live behavior, and full env reference—bookmark them.",
];
